# --- Input: Prepared Gapminder 2007 Data ---
gapminder_2007_input: "data/generated/gapminder_2007_prepared.parquet"

# --- Output: Summary Statistics ---
summary_statistics_csv: "output/summary_statistics.csv"
summary_statistics_pickle: "output/summary_statistics.pickle"

# --- Output: Figure ---
figure1_save_path: "output/figure1_replication.png"
figure1_pickle_path: "output/figure1_replication.pickle"