# --- Input: Prepared Gapminder 2007 Data ---
gapminder_2007_input: "data/generated/gapminder_2007_prepared.parquet"

# --- Output: Summary Statistics ---
summary_statistics_pickle: "output/summary_statistics.pickle"

# --- Output: Figure ---
gapminder_figure_png: "output/gapminder_figure.png"