## Task 1&2
# CRSP Daily Stock Data (Annual update)
crsp_vars:
  - permno # Unique Identifier to match
  - date
  - ret  # Daily return from CRSP, price (`PCR`) not used for simplicity
crsp_filter:
  - "date >= '1972-01-01'"
  - "date <= '2023-12-31'"
crsp_save_path: 'data/pulled/crsp_daily_stock_returns.parquet'
crsp_save_path_csv: 'data/pulled/crsp_daily_stock_returns.csv'

# Compustat Fundamentals - Quarterly (Daily Update)
fundq_vars:
  - gvkey # Unique Identifier to match
  - datadate
  - conm  # Company name
  - tic  # Ticker symbol
  - rdq  # Reported Date for Earnings Announcements - for Earnings Announcement Definition
  - fyr  # Fiscal Year-End Indicator (Table 2 Panel C-D Replication)
fundq_filter: 
fundq_save_path: 'data/pulled/compustat_fundq_1972_2023.parquet'
fundq_save_path_csv: 'data/pulled/compustat_fundq_1972_2023.csv'


## Task 3
# Basically, adapt the variables from CRSP/Compustat above to WSCP/Datastream, since same methodology.
# Worldscope - Stock Data (Quarterly Update)
wrds_ws_stock_vars:
  - code # The QA primary mapping code across all Worldscope tables
  - year_
  - item6105 # Worldscope Permanent ID (referred to as WsSctyPPI in Datastream) - unique identifier I use to link data
  - item5901 # EARNINGS PER SHARE - REPORT DATE - QUARTER 1 (item5901) - equivalent to RDQ Compustat
  - item5902 # EARNINGS PER SHARE - REPORT DATE - QUARTER 2 (item5902)
  - item5903 # EARNINGS PER SHARE - REPORT DATE - QUARTER 3 (item5903)
  - item5904 # EARNINGS PER SHARE - REPORT DATE - QUARTER 4 (item5904)
wrds_ws_stock_filter:

worldscope_sample_save_path: 'data/pulled/wrds_ws_stock.parquet'
worldscope_sample_save_path_csv: 'data/pulled/wrds_ws_stock.csv'

# Datastream Daily Stock File (Weekly Update)
ds_vars:
  - marketdate # Date of the price (marketdate)
  - infocode # The QA primary mapping code across all Datastream tables
  - region # Country code indicating where the security is traded to futher filter for Canada
  - typecode # Code indicating the type of equity
  - ret # Percentage change in RI based on the RI from last trading date 
  - dscode # Additional Datastream unique identifier (potentially useful for linking) - I did not use in the end, because the linked dataset does not get the variable


ds_filter:
  - "marketdate >= '1980-01-01'" # Starting with 1980 since year_ starts within this range - helps to omit many NAs
  - "marketdate <= '2023-12-31'"
  - "region = 'CA'" # My chosen country
  - "typecode = 'EQ'" # Filter for Common Equity (Regular Stock) to match with CRSP

datastream_sample_save_path: 'data/pulled/wrds_ds2dsf.parquet'
datastream_sample_save_path_csv: 'data/pulled/wrds_ds2dsf.csv'

link_ds_ws_save_path: 'data/pulled/wrds_link_ds_ws.parquet'
link_ds_ws_save_path_csv: 'data/pulled/wrds_link_ds_ws.csv'